In [97]:
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator
import numpy as np

In [98]:
data_file = '/home/hasitha/Desktop/data/fabric/fabric_400/results/contact_fabric_400_2400.dat'
with open(data_file, 'r') as file:
    cns_str = file.readlines()
    cns = []
    for cn_str in cns_str:
        cn = cn_str.split()
        cns.append([float(n) for n in cn])
    cns = np.array(cns)

In [99]:
def delta(i,j):
    return 1 if i == j else 0

In [100]:
def D_ij(i,j):
    N = len(cns)
    return np.sum([cn[i]*cn[j] for cn in cns])/N

In [102]:
def F_ij(i,j):
    return 1.5*(5*D_ij(i,j)-delta(i,j))

In [103]:
F_ij(0,0)

0.7290497558108111

In [79]:
F2 = np.zeros((3,3))
for i in np.arange(3):
    for j in np.arange(3):
        F2[i,j] = F_ij(i,j)

In [94]:
D2 = np.zeros((3,3))
for i in np.arange(3):
    for j in np.arange(3):
        D2[i,j] = D_ij(i,j)
print(D2)

[[ 2.97206634e-01  2.08784987e-03 -1.98412871e-05]
 [ 2.08784987e-03  2.60653350e-01  3.99759715e-03]
 [-1.98412871e-05  3.99759715e-03  4.42140359e-01]]


In [83]:
def I_ijkl(i,j,k,l):
    return (delta(i,j)*delta(k,l) + delta(i,k)*delta(j,l) + delta(i,l)*delta(j,k))/3.

In [85]:
def D_ijkl(i,j,k,l):
    N = len(cns)
    return np.sum([cn[i]*cn[j]*cn[k]*cn[l] for cn in cns])/N

In [87]:
def F_ijkl(i,j,k,l):
    first = 21*D_ijkl(i,j,k,l)
    second = (delta(i,j)*D_ij(k,l) + delta(i,k)*D_ij(j,l) + delta(i,l)*D_ij(k,j) + \
              delta(j,k)*D_ij(i,l) + delta(j,l)*D_ij(i,k) + delta(k,l)*D_ij(i,j) )*14/6
    third = I_ijkl(i,j,k,l)
    return (first + second + third)*15/8

In [90]:
F4 = np.array([[F_ijkl(0,0,0,0), F_ijkl(0,0,1,1), F_ijkl(0,0,2,2), F_ijkl(0,0,1,2), F_ijkl(0,0,0,2), F_ijkl(0,0,0,1)],
            [F_ijkl(1,1,0,0), F_ijkl(1,1,1,1), F_ijkl(1,1,2,2), F_ijkl(1,1,1,2), F_ijkl(1,1,0,2), F_ijkl(1,1,0,1)],
            [F_ijkl(2,2,0,0), F_ijkl(2,2,1,1), F_ijkl(2,2,2,2), F_ijkl(2,2,1,2), F_ijkl(2,2,0,2), F_ijkl(2,2,0,1)],
            [F_ijkl(1,2,0,0), F_ijkl(1,2,1,1), F_ijkl(1,2,2,2), F_ijkl(1,2,1,2), F_ijkl(1,2,0,2), F_ijkl(1,2,0,1)],
            [F_ijkl(0,2,0,0), F_ijkl(0,2,1,1), F_ijkl(0,2,2,2), F_ijkl(0,2,1,2), F_ijkl(0,2,0,2), F_ijkl(0,2,0,1)],
            [F_ijkl(0,1,0,0), F_ijkl(0,1,1,1), F_ijkl(0,1,2,2), F_ijkl(0,1,1,2), F_ijkl(0,1,0,2), F_ijkl(0,1,0,1)]])

In [95]:
D4 = np.array([[D_ijkl(0,0,0,0), D_ijkl(0,0,1,1), D_ijkl(0,0,2,2), D_ijkl(0,0,1,2), D_ijkl(0,0,0,2), D_ijkl(0,0,0,1)],
            [D_ijkl(1,1,0,0), D_ijkl(1,1,1,1), D_ijkl(1,1,2,2), D_ijkl(1,1,1,2), D_ijkl(1,1,0,2), D_ijkl(1,1,0,1)],
            [D_ijkl(2,2,0,0), D_ijkl(2,2,1,1), D_ijkl(2,2,2,2), D_ijkl(2,2,1,2), D_ijkl(2,2,0,2), D_ijkl(2,2,0,1)],
            [D_ijkl(1,2,0,0), D_ijkl(1,2,1,1), D_ijkl(1,2,2,2), D_ijkl(1,2,1,2), D_ijkl(1,2,0,2), D_ijkl(1,2,0,1)],
            [D_ijkl(0,2,0,0), D_ijkl(0,2,1,1), D_ijkl(0,2,2,2), D_ijkl(0,2,1,2), D_ijkl(0,2,0,2), D_ijkl(0,2,0,1)],
            [D_ijkl(0,1,0,0), D_ijkl(0,1,1,1), D_ijkl(0,1,2,2), D_ijkl(0,1,1,2), D_ijkl(0,1,0,2), D_ijkl(0,1,0,1)]])